### ISSUE TITLE
Impossible to have multiple chargebee instances with different ENV variables

### ISSUE THREAD

**Issue by armen19932** [chargebee/chargebee-typescript#42]
Hi,
I need to have multiple instances in my application, but I can't implement it, because when I'm setting up the instances and configuring it, as ENV it is getting the last ENV variable I've set.
I've investigated the problem and I find, that the _env in Chargebee class is static, and always it is getting the last configuration

**Comment by SevanEl** [comment]
@armen19932
I checked the code and in fact there cannot be 2 instances of the `ChargeBee` class with different environments. Since the `_env` is a static member of the `ChargeBee` class, the call to `ChargeBee.configure()` method is going to override the existing values in the static `_env` member of the ChargeBee, thus effecting the environment for all instances of `ChargeBee` class.

On the other hand, though the above mentioned issue is real, and does not allow you to have two different instances of the `ChargeBee` class to be used for EU and US payments, you can have just one instance, and use the [`RequestWrapper.request()`](https://github.com/chargebee/chargebee-typescript/blob/f49eb78c4af8f8746caed4bb45936029e7a17f18/src/request_wrapper.ts#L50) method to pass the expected environment variables upon each call.

```typescript
    public request(callBack=undefined, envOptions?): Promise<T> {
        let env = {};
        let jsonConstructor =  {}.constructor;
        Util.extend(true, env, this.envArg);
        if (typeof envOptions !== 'undefined') {
            Util.extend(true, env, envOptions);
        } else if(typeof callBack !== 'undefined' && callBack.constructor === jsonConstructor && !Util.isFunction(callBack)){
            Util.extend(true, env, callBack);
            callBack = undefined;
        }
        let deferred = Util.createDeferred<T>(callBack);
        let urlIdParam = this.apiCall.hasIdInUrl ? this.args[0] : null;
        let params = this.apiCall.hasIdInUrl ? this.args[1] : this.args[0];
        if (typeof callBack !== 'undefined' && !Util.isFunction(callBack)) {
            throw new Error('The callback parameter passed is incorrect.');
        }
        function callBackWrapper(err, response) {
            if (err) {
                deferred.reject(err);
            } else {
                deferred.resolve(response);
            }
        }
        Core.makeApiRequest(env, callBackWrapper, this.apiCall.httpMethod, this.apiCall.urlPrefix, this.apiCall.urlSuffix, urlIdParam, params, this.httpHeaders, this.apiCall.isListReq);
        return deferred.promise;
    };
```

As you can see, the `request()` method has an `envOptions` parameter which can be used to pass the expected environmental options upon each call. The implementation checks for `typeof envOptions !== 'undefined'` and overrides the values with the ones from the `this.envArg`.

So, having only one `ChargeBee` class instance, you can do as follows:

```typescript
import { ChargeBee } from 'chargebee-typescript';
const chargebee = new ChargeBee();

const { customerEU } = await chargebee.customer
  .create({
    email: 'john@test.eu',
    // other params
  })
  .request(callBack=undefined, { site: 'YOUR_EU_SITE_NAME', api_key: 'YOUR_EU_API_KEY' });

const { customerUS } = await chargebee.customer
  .create({
    email: 'john@test.us',
    // other params
  })
  .request(callBack=undefined, { site: 'YOUR_US_SITE_NAME', api_key: 'YOUR_US_API_KEY' });
```

**Note:** This does not solve the issue of nothing being able to have two separate instances of `ChargeBee` class, each with its own environment values, but can work as a workaround.

**Comment by cb-sriramthiagarajan** [comment]
Thank you @armen19932. I can see that the way given in our Docs works as well. Sharing a sample code snippet below.

```
chargebee.configure({
  api_key: "site1-api-key",
  site: "site1"
});

try {
    const result = await chargebee.customer
      .list({
        limit: 1
      })
      .request(undefined, {
        site: "site2",
        api_key: "site2-api-key"
      });
    console.log("site2 customer", result.list[0]?.customer.id);
  } catch (error) {
    console.log(error);
  }

  try {
    const result = await chargebee.customer
      .list({
        limit: 1
      })
      .request();
    console.log("site1 customer", result.list[0]?.customer.id);
  } catch (error) {
    console.log(error);
  }
  ```

I'll go ahead and close this issue for now. Please feel free to reopen or create a new one if you face this again. Thanks.
